/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mocks from "./MOCKS";
export type { mocks };
import type * as space from "./Space";
export type { space };
import type * as vault from "./Vault";
export type { vault };
import type * as ykit from "./Ykit";
export type { ykit };
