/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as ethLockerSol from "./ETHLocker.sol";
export * as ethLockerPrivSol from "./ETHLockerPriv.sol";
export * as lockerPassSol from "./LockerPass.sol";
