/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../../common";
import type {
  ADRSB,
  ADRSBInterface,
} from "../../../../YemoKit/Helpers/ADRSB.sol/ADRSB";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_owner",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_key",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "_adrs",
        type: "address",
      },
    ],
    name: "adrs",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    name: "dataStore",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "intd",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60806040526000805460ff1916905534801561001a57600080fd5b506040516102c23803806102c283398101604081905261003991610064565b600080546001600160a01b0390921661010002610100600160a81b0319909216919091179055610094565b60006020828403121561007657600080fd5b81516001600160a01b038116811461008d57600080fd5b9392505050565b61021f806100a36000396000f3fe608060405234801561001057600080fd5b506004361061004c5760003560e01c8063401ac1cc146100515780638da5cb5b146100975780639f36c046146100af578063f20df5ae146100cc575b600080fd5b61007a61005f366004610194565b6001602052600090815260409020546001600160a01b031681565b6040516001600160a01b0390911681526020015b60405180910390f35b60005461007a9061010090046001600160a01b031681565b6000546100bc9060ff1681565b604051901515815260200161008e565b6100bc6100da3660046101ad565b6000805460ff1661014b576040517f08c379a000000000000000000000000000000000000000000000000000000000815260206004820152600a60248201527f4e6f7420696e6974656400000000000000000000000000000000000000000000604482015260640160405180910390fd5b600083815260016020526040812080547fffffffffffffffffffffffff0000000000000000000000000000000000000000166001600160a01b0385161790555060019392505050565b6000602082840312156101a657600080fd5b5035919050565b600080604083850312156101c057600080fd5b8235915060208301356001600160a01b03811681146101de57600080fd5b80915050925092905056fea26469706673582212201c33c3eb8f6b5fe0da0afd69759d351284a3b8a7abcb1fe42a433f0cd77c682364736f6c63430008140033";

type ADRSBConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ADRSBConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ADRSB__factory extends ContractFactory {
  constructor(...args: ADRSBConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    _owner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ADRSB> {
    return super.deploy(_owner, overrides || {}) as Promise<ADRSB>;
  }
  override getDeployTransaction(
    _owner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(_owner, overrides || {});
  }
  override attach(address: string): ADRSB {
    return super.attach(address) as ADRSB;
  }
  override connect(signer: Signer): ADRSB__factory {
    return super.connect(signer) as ADRSB__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ADRSBInterface {
    return new utils.Interface(_abi) as ADRSBInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): ADRSB {
    return new Contract(address, _abi, signerOrProvider) as ADRSB;
  }
}
