/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { SimpleVault__factory } from "./SimpleVault__factory";
export { YBaseVault__factory } from "./YBaseVault__factory";
