/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as locker from "./Locker";
export type { locker };
import type * as vault from "./Vault";
export type { vault };
export type { MultiSigWallet } from "./MultiSigWallet";
