/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface YKitFactoryInterface extends utils.Interface {
  functions: {
    "_AdvancedERC20Locker()": FunctionFragment;
    "_AdvancedEscrow()": FunctionFragment;
    "_ContractFactory()": FunctionFragment;
    "_ETHLocker()": FunctionFragment;
    "createNewAdvancedERC20Locker(address,address,address,uint256)": FunctionFragment;
    "createNewAdvancedEscrow(address,address,uint256)": FunctionFragment;
    "createNewContractFactory(address)": FunctionFragment;
    "createNewETHLocker(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "_AdvancedERC20Locker"
      | "_AdvancedEscrow"
      | "_ContractFactory"
      | "_ETHLocker"
      | "createNewAdvancedERC20Locker"
      | "createNewAdvancedEscrow"
      | "createNewContractFactory"
      | "createNewETHLocker"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "_AdvancedERC20Locker",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "_AdvancedEscrow",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "_ContractFactory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "_ETHLocker",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createNewAdvancedERC20Locker",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createNewAdvancedEscrow",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createNewContractFactory",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "createNewETHLocker",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "_AdvancedERC20Locker",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_AdvancedEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_ContractFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "_ETHLocker", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createNewAdvancedERC20Locker",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createNewAdvancedEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createNewContractFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createNewETHLocker",
    data: BytesLike
  ): Result;

  events: {};
}

export interface YKitFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: YKitFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    _AdvancedERC20Locker(overrides?: CallOverrides): Promise<[string]>;

    _AdvancedEscrow(overrides?: CallOverrides): Promise<[string]>;

    _ContractFactory(overrides?: CallOverrides): Promise<[string]>;

    _ETHLocker(overrides?: CallOverrides): Promise<[string]>;

    createNewAdvancedERC20Locker(
      owner: PromiseOrValue<string>,
      token: PromiseOrValue<string>,
      feeRecipient: PromiseOrValue<string>,
      penaltyFee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    createNewAdvancedEscrow(
      owner: PromiseOrValue<string>,
      depositToken: PromiseOrValue<string>,
      minDepositAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    createNewContractFactory(
      owner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    createNewETHLocker(
      owner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  _AdvancedERC20Locker(overrides?: CallOverrides): Promise<string>;

  _AdvancedEscrow(overrides?: CallOverrides): Promise<string>;

  _ContractFactory(overrides?: CallOverrides): Promise<string>;

  _ETHLocker(overrides?: CallOverrides): Promise<string>;

  createNewAdvancedERC20Locker(
    owner: PromiseOrValue<string>,
    token: PromiseOrValue<string>,
    feeRecipient: PromiseOrValue<string>,
    penaltyFee: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  createNewAdvancedEscrow(
    owner: PromiseOrValue<string>,
    depositToken: PromiseOrValue<string>,
    minDepositAmount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  createNewContractFactory(
    owner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  createNewETHLocker(
    owner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    _AdvancedERC20Locker(overrides?: CallOverrides): Promise<string>;

    _AdvancedEscrow(overrides?: CallOverrides): Promise<string>;

    _ContractFactory(overrides?: CallOverrides): Promise<string>;

    _ETHLocker(overrides?: CallOverrides): Promise<string>;

    createNewAdvancedERC20Locker(
      owner: PromiseOrValue<string>,
      token: PromiseOrValue<string>,
      feeRecipient: PromiseOrValue<string>,
      penaltyFee: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    createNewAdvancedEscrow(
      owner: PromiseOrValue<string>,
      depositToken: PromiseOrValue<string>,
      minDepositAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    createNewContractFactory(
      owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    createNewETHLocker(
      owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    _AdvancedERC20Locker(overrides?: CallOverrides): Promise<BigNumber>;

    _AdvancedEscrow(overrides?: CallOverrides): Promise<BigNumber>;

    _ContractFactory(overrides?: CallOverrides): Promise<BigNumber>;

    _ETHLocker(overrides?: CallOverrides): Promise<BigNumber>;

    createNewAdvancedERC20Locker(
      owner: PromiseOrValue<string>,
      token: PromiseOrValue<string>,
      feeRecipient: PromiseOrValue<string>,
      penaltyFee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    createNewAdvancedEscrow(
      owner: PromiseOrValue<string>,
      depositToken: PromiseOrValue<string>,
      minDepositAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    createNewContractFactory(
      owner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    createNewETHLocker(
      owner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    _AdvancedERC20Locker(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _AdvancedEscrow(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    _ContractFactory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    _ETHLocker(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    createNewAdvancedERC20Locker(
      owner: PromiseOrValue<string>,
      token: PromiseOrValue<string>,
      feeRecipient: PromiseOrValue<string>,
      penaltyFee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    createNewAdvancedEscrow(
      owner: PromiseOrValue<string>,
      depositToken: PromiseOrValue<string>,
      minDepositAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    createNewContractFactory(
      owner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    createNewETHLocker(
      owner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
