/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../../common";

export interface YKInterface extends utils.Interface {
  functions: {
    "ddsp()": FunctionFragment;
    "dplr()": FunctionFragment;
    "eemt()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "ddsp" | "dplr" | "eemt"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "ddsp", values?: undefined): string;
  encodeFunctionData(functionFragment: "dplr", values?: undefined): string;
  encodeFunctionData(functionFragment: "eemt", values?: undefined): string;

  decodeFunctionResult(functionFragment: "ddsp", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "dplr", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "eemt", data: BytesLike): Result;

  events: {};
}

export interface YK extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: YKInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    ddsp(overrides?: CallOverrides): Promise<[string]>;

    dplr(overrides?: CallOverrides): Promise<[string]>;

    eemt(overrides?: CallOverrides): Promise<[string]>;
  };

  ddsp(overrides?: CallOverrides): Promise<string>;

  dplr(overrides?: CallOverrides): Promise<string>;

  eemt(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    ddsp(overrides?: CallOverrides): Promise<string>;

    dplr(overrides?: CallOverrides): Promise<string>;

    eemt(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    ddsp(overrides?: CallOverrides): Promise<BigNumber>;

    dplr(overrides?: CallOverrides): Promise<BigNumber>;

    eemt(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    ddsp(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    dplr(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    eemt(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
