/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  OOwn,
  OOwnInterface,
} from "../../../../contracts/YemoVault/YemoVault.sol/OOwn";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_nOwn",
        type: "address",
      },
    ],
    name: "cngOwn",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class OOwn__factory {
  static readonly abi = _abi;
  static createInterface(): OOwnInterface {
    return new utils.Interface(_abi) as OOwnInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): OOwn {
    return new Contract(address, _abi, signerOrProvider) as OOwn;
  }
}
