/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  Onl,
  OnlInterface,
} from "../../../../YemoKit/Helpers/Onlntd.sol/Onl";

const _abi = [
  {
    inputs: [],
    name: "intd",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class Onl__factory {
  static readonly abi = _abi;
  static createInterface(): OnlInterface {
    return new utils.Interface(_abi) as OnlInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Onl {
    return new Contract(address, _abi, signerOrProvider) as Onl;
  }
}
