/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../../common";
import type {
  DSNt,
  DSNtInterface,
} from "../../../../YemoVur/Ykit/DDSP.sol/DSNt";

const _abi = [
  {
    anonymous: true,
    inputs: [
      {
        indexed: true,
        internalType: "bytes4",
        name: "sig",
        type: "bytes4",
      },
      {
        indexed: true,
        internalType: "address",
        name: "guy",
        type: "address",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "foo",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "bar",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "wad",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "fax",
        type: "bytes",
      },
    ],
    name: "LogNote",
    type: "event",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b50603f80601d6000396000f3fe6080604052600080fdfea2646970667358221220694f39a0e4324d0451d1fbf115e57f20e94247fff35c2801b6001e3ef41c1a5164736f6c63430008140033";

type DSNtConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: DSNtConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class DSNt__factory extends ContractFactory {
  constructor(...args: DSNtConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<DSNt> {
    return super.deploy(overrides || {}) as Promise<DSNt>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): DSNt {
    return super.attach(address) as DSNt;
  }
  override connect(signer: Signer): DSNt__factory {
    return super.connect(signer) as DSNt__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): DSNtInterface {
    return new utils.Interface(_abi) as DSNtInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): DSNt {
    return new Contract(address, _abi, signerOrProvider) as DSNt;
  }
}
